#!/usr/bin/env python3
"""Generate the Codex wrapper and deterministic ``.skill`` package."""

from __future__ import annotations

import argparse
from io import BytesIO
from pathlib import Path
import re
import sys
import unicodedata
import zipfile


SKILL_DIR_NAME = "helix-rew-tuner"
ARCHIVE_NAME = f"{SKILL_DIR_NAME}.skill"
FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)
TEXT_SUFFIXES = {".json", ".md", ".py", ".toml", ".txt", ".yaml", ".yml"}

SKILL_WRAPPER = """\
---
name: helix-rew-tuner
description: >-
  Use when diagnosing, tuning, or verifying Helix / Audiotec Fischer car-audio
  DSP systems from REW measurements; editing or validating `.afpx` or beta
  `.pct6` tune files; or handling supported beta Alpine `.jssh` presets,
  crossover, imaging, bass, phase, level, target-curve, or measurement-quality
  problems.
---

# Helix / REW measurement-driven auto-tuner

Use this skill for supported Helix, Audiotec Fischer, and beta Alpine car-audio
DSP work driven by REW measurements or supported tune files.

Before analyzing data, proposing changes, or writing a tune, read
`references/core_workflow.md` in full and follow it as the canonical workflow.
Paths in that workflow are relative to this skill directory. Read each routed
format or methodology reference before its first required operation.

Alpine `.jssh` support remains part of this skill. Treat it as beta and follow
the format-specific preflight, writable-limit, Q-snap, preservation, and
hardware read-back requirements in `references/alpine_jssh_format.md`.
"""

OPENAI_METADATA = """\
interface:
  display_name: "Helix REW Tuner"
  short_description: "Diagnose and tune car DSPs from REW data"
  default_prompt: "Use $helix-rew-tuner to diagnose my REW measurements and propose a conservative, verified DSP tune."
"""


class BuildError(ValueError):
    """Raised when source inputs cannot produce a valid skill."""


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise BuildError(f"cannot read {path}: {exc}") from exc


def _heading_slug(heading: str) -> str:
    heading = re.sub(r"<[^>]+>", "", heading)
    heading = heading.replace("`", "").strip().lower()
    kept: list[str] = []
    for char in heading:
        category = unicodedata.category(char)
        if char in {" ", "-", "_"} or category[0] in {"L", "N"}:
            kept.append(char)
    return re.sub(r"[\s-]+", "-", "".join(kept)).strip("-")


def _validate_methodology_anchors(path: Path) -> None:
    text = _read_text(path)
    counts: dict[str, int] = {}
    anchors: set[str] = set()
    for match in re.finditer(r"(?m)^#{1,6}\s+(.+?)\s*#*\s*$", text):
        base = _heading_slug(match.group(1))
        if not base:
            continue
        count = counts.get(base, 0)
        counts[base] = count + 1
        anchors.add(base if count == 0 else f"{base}-{count}")

    for target in re.findall(r"\[[^\]\r\n]+\]\(#([^)\s]+)\)", text):
        if target not in anchors:
            raise BuildError(f"unresolved Markdown anchor #{target} in {path}")


def _validate_sources(root: Path) -> None:
    skill = root / SKILL_DIR_NAME
    required = (
        skill / "references" / "core_workflow.md",
        skill / "references" / "methodology.md",
    )
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise BuildError("missing required skill file(s): " + ", ".join(missing))
    _validate_methodology_anchors(skill / "references" / "methodology.md")


def _agents_bytes(root: Path) -> bytes:
    core = _read_text(root / SKILL_DIR_NAME / "references" / "core_workflow.md")
    core = core.rstrip() + "\n"
    wrapper = f"""\
<!-- Generated by tools/build_skill.py from helix-rew-tuner/references/core_workflow.md. -->
<!-- Do not edit AGENTS.md directly; run: python tools/build_skill.py --write -->

This repository contains the `$helix-rew-tuner` skill. Apply it when the user
asks to diagnose, tune, or verify a supported Helix or Alpine car-audio DSP
from REW measurements or supported tune files. Trigger on that intent even if
the user does not name the skill or file formats explicitly.

Repository paths in the canonical workflow are relative to
`helix-rew-tuner/`. Use the scripts there as the deterministic layer, and read
the routed references before proposing or writing a change.

{core}"""
    return wrapper.encode("utf-8")


def _package_paths(skill_dir: Path) -> list[Path]:
    paths: list[Path] = []
    for path in skill_dir.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(skill_dir)
        if "__pycache__" in relative.parts or path.suffix in {".pyc", ".pyo"}:
            continue
        paths.append(path)
    return sorted(paths, key=lambda path: path.relative_to(skill_dir).as_posix())


def _normalize_text_bytes(data: bytes) -> bytes:
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def _packaged_file_bytes(path: Path) -> bytes:
    data = path.read_bytes()
    if path.suffix.lower() in TEXT_SUFFIXES:
        return _normalize_text_bytes(data)
    return data


def _archive_bytes(root: Path) -> bytes:
    skill_dir = root / SKILL_DIR_NAME
    output = BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_STORED) as package:
        for path in _package_paths(skill_dir):
            relative = path.relative_to(root).as_posix()
            info = zipfile.ZipInfo(relative, FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            package.writestr(info, _packaged_file_bytes(path))
    return output.getvalue()


def write(root: Path) -> None:
    root = root.resolve()
    _validate_sources(root)
    skill = root / SKILL_DIR_NAME
    (skill / "agents").mkdir(parents=True, exist_ok=True)
    (skill / "SKILL.md").write_bytes(SKILL_WRAPPER.encode("utf-8"))
    (skill / "agents" / "openai.yaml").write_bytes(OPENAI_METADATA.encode("utf-8"))
    (root / "AGENTS.md").write_bytes(_agents_bytes(root))
    (root / ARCHIVE_NAME).write_bytes(_archive_bytes(root))


def check(root: Path) -> list[str]:
    root = root.resolve()
    _validate_sources(root)
    failures: list[str] = []
    skill = root / SKILL_DIR_NAME
    skill_md = skill / "SKILL.md"
    openai = skill / "agents" / "openai.yaml"
    agents = root / "AGENTS.md"
    archive = root / ARCHIVE_NAME
    if not skill_md.is_file() or _normalize_text_bytes(
        skill_md.read_bytes()
    ) != SKILL_WRAPPER.encode("utf-8"):
        failures.append("helix-rew-tuner/SKILL.md is stale; run python tools/build_skill.py --write")
    if not openai.is_file() or _normalize_text_bytes(
        openai.read_bytes()
    ) != OPENAI_METADATA.encode("utf-8"):
        failures.append(
            "helix-rew-tuner/agents/openai.yaml is stale; run python tools/build_skill.py --write"
        )
    if not agents.is_file() or _normalize_text_bytes(
        agents.read_bytes()
    ) != _agents_bytes(root):
        failures.append("AGENTS.md is stale; run python tools/build_skill.py --write")
    if not archive.is_file() or archive.read_bytes() != _archive_bytes(root):
        failures.append(
            f"{ARCHIVE_NAME} is stale; run python tools/build_skill.py --write"
        )
    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="validate without writing")
    mode.add_argument("--write", action="store_true", help="regenerate build outputs")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args(argv)
    try:
        if args.write:
            write(args.root)
            print("generated SKILL.md, agents/openai.yaml, AGENTS.md, and helix-rew-tuner.skill")
            return 0
        failures = check(args.root)
    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if failures:
        for failure in failures:
            print(f"ERROR: {failure}", file=sys.stderr)
        return 1
    print("generated files and package are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
